Show unsubscribed user link in notification email
dreamwidth/dreamwidth pull request #3150
Opened 2023-06-24 22:34 UTC by cmho

CODE TOUR: If you're receiving notification emails for when someone has unsubscribed or removed their access, the emails will now give a link to the other user's journal to remind you who they are.

Closes #3060

2023-07-09 01:10 UTC, kareila commented on cgi-bin/LJ/Event/RemovedFromCircle.pm
>                      "$LJ::SITEROOT/circle/$postername/edit"
So looking at how format_options works: if the first element here is 0, it doesn't show at all, so this should actually be `[ 1, $journal_url ]` and `!$u->watches( $self->fromuser ) ? 0 : 2` in order to do what you want. (Same also for trusts.)

2023-07-27 15:07 UTC, kareila requested changes
You got the first half of my suggested changes but not the second half. Sorry I wasn't more verbose in my original review!

2023-07-28 03:33 UTC, cmho commented on cgi-bin/LJ/Event/RemovedFromCircle.pm
> +                'esn.show_unsubscribed_journal' => [ 0, $journal_url ],
👍🏼 got it this time, don't know how I missed that >_>

2023-07-28 03:55 UTC, kareila approved these changes
Okay, tested this and seems to behave as desired! 👍

2023-07-28 03:57 UTC, merged